- id: '1572719745182'
  alias: Mach Toaster nach 5 Minuten aus
  description: ''
  trigger:
  - device_id: cf983160a5b6426d8053f5547d3857e2
    domain: switch
    entity_id: switch.toaster
    platform: device
    type: turned_on
  condition: []
  action:
  - delay: 00:05:00
  - device_id: cf983160a5b6426d8053f5547d3857e2
    domain: switch
    entity_id: switch.toaster
    type: turn_off
- id: '1572821002116'
  alias: Licht aus im Urlaub
  description: ''
  trigger:
  - at: '23:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - delay: '{{ 0 ~ ":" ~ ((range(5, 30) | random) | int)  ~ ":" ~  ((range(5, 55)
      | random) | int) }}'
  - data: {}
    entity_id: switch.couch
    service: switch.turn_off
  - delay: '{{ 0 ~ ":" ~ ((range(5, 30) | random) | int)  ~ ":" ~  ((range(5, 55)
      | random) | int) }}'
  - data: {}
    entity_id: switch.tischlampe1
    service: switch.turn_off
  - delay: '{{ 0 ~ ":" ~ ((range(5, 30) | random) | int)  ~ ":" ~  ((range(5, 55)
      | random) | int) }}'
  - data: {}
    entity_id: light.living_room
    service: light.turn_off
- id: '1572821325365'
  alias: Küchengeräte ausmachen beim Verlassen der Wohnung
  description: ''
  trigger:
  - entity_id: device_tracker.pixel_2
    event: leave
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.lav_yu
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.lav_yu
      state: not_home
    - condition: state
      entity_id: device_tracker.pixel_2
      state: not_home
  action:
  - device_id: b2fd6988e50d410cb4679a304ee8fccb
    domain: light
    entity_id: light.kitchen_2
    type: turn_off
- id: '1574201751222'
  alias: Heizung am Morgen
  description: ''
  trigger:
  - at: 08:15
    platform: time
  condition:
  - condition: state
    entity_id: device_tracker.192_168_178_22
    state: home
  - condition: state
    entity_id: device_tracker.lav_yu
    state: home
  action:
  - data:
      entity_id: climate.bathroom
    service: script.heizung
- id: '1574287615042'
  alias: Heizung Nachtabsenkung
  description: ''
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.bathroom
    service: climate.turn_off
- id: '1574546775193'
  alias: Licht anmachen bei Ankunft
  description: ''
  trigger:
  - entity_id: device_tracker.ubyiyegc_goesta
    platform: state
    to: home
  - entity_id: device_tracker.lav_yu
    platform: state
    to: home
  - entity_id: device_tracker.192_168_178_22
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - before: '23:59'
    condition: time
  action:
  - device_id: 152990169e864794a79e0931a2ee677d
    domain: switch
    entity_id: switch.couch
    type: turn_on
- id: '1574548544134'
  alias: Test WLAN Login
  description: ''
  trigger:
  - entity_id: device_tracker.192_168_178_22
    platform: state
    to: home
  condition: []
  action:
  - device_id: 152990169e864794a79e0931a2ee677d
    domain: switch
    entity_id: switch.couch
    type: turn_on
- id: '1574638647047'
  alias: Wasserkocher am Morgen
  description: ''
  trigger:
  - at: 08:45
    platform: time
  condition:
  - condition: state
    entity_id: device_tracker.192_168_178_22
    state: home
  action:
  - device_id: 434e558985a9451eb8587f227f156b2d
    domain: switch
    entity_id: switch.kettle
    type: turn_on
- id: '1575756920713'
  alias: Licht am Abend
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: state
      entity_id: device_tracker.lav_yu
      state: home
    - condition: state
      entity_id: device_tracker.192_168_178_22
      state: home
  action:
  - data: {}
    entity_id: switch.couch
    service: switch.turn_on
  - data: {}
    entity_id: switch.tischlampe1
    service: switch.turn_on
  - entity_id: scene.muggeln
    service: scene.turn_on
  mode: single
- id: '1577043804696'
  alias: Licht bei Bewegung anmachen
  description: ''
  trigger:
  - device_id: 44e7b1bda76548308ec8ad65fb3cbd4c
    domain: binary_sensor
    entity_id: binary_sensor.presence
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: motion
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - after: '23:30'
    before: 06:00
    condition: time
  action:
  - device_id: 152990169e864794a79e0931a2ee677d
    domain: switch
    entity_id: switch.couch
    type: turn_on
- id: '1577317589266'
  alias: Mach Heizung im Bad nach 30 Minuten aus
  description: ''
  trigger:
  - entity_id: climate.bathroom
    from: 'off'
    platform: state
  condition: []
  action:
  - delay: 00:30:00
  - alias: ''
    data:
      entity_id: climate.bathroom
    entity_id: climate.bathroom
    service: climate.turn_off
  - entity_id: input_boolean.bath_heating
    service: input_boolean.turn_off
- id: '1577476640677'
  alias: Alarm, when motion detected and nobody is at home
  description: ''
  trigger:
  - device_id: 44e7b1bda76548308ec8ad65fb3cbd4c
    domain: binary_sensor
    entity_id: binary_sensor.presence
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: motion
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.lav_yu
      state: not_home
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    - condition: state
      entity_id: device_tracker.192_168_178_22
      state: not_home
  action:
  - data:
      message: Alarm!
    service: notify.mobile_app_pixel_2
  - data: {}
    entity_id: script.1577400292371
    service: script.turn_on
- id: '1579640771333'
  alias: Mach Heizung aus Fallback
  description: ''
  trigger:
  - entity_id: climate.bathroom
    from: 'off'
    platform: state
  condition: []
  action:
  - delay: 00:31:00
  - data:
      entity_id: climate.bathroom
    entity_id: climate.bathroom
    service: climate.turn_off
  - entity_id: input_boolean.bath_heating
    service: input_boolean.turn_off
- id: '1589387016661'
  alias: Wake me up
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.alarm_hours_int'') == states(''sensor.current_hours_int'')
      and states(''sensor.alarm_minutes_int'')|int - states(''sensor.current_minutes_int'')|int
      == 1}}'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - data: {}
    entity_id: switch.musicbox
    service: switch.turn_on
  - delay: 00:01:00
  - data:
      media_content_id: https://www.youtube.com/watch?v=xXDC5xGy8wo
      media_content_type: video/youtube
    entity_id: media_player.wohnzimmer
    service: media_extractor.play_media
  - delay: 00:00:05
  - data:
      entity_id: media_player.wohnzimmer
      volume_level: 0.4
    entity_id: media_player.wohnzimmer
    service: media_player.volume_set
  mode: single
- id: '1590432786127'
  alias: Switch off music box completely when off
  description: ''
  trigger:
  - entity_id: media_player.wohnzimmer
    for: 00:05:00
    platform: state
    to: idle
  - entity_id: media_player.wohnzimmer
    for: 00:05:00
    platform: state
    to: 'off'
  - entity_id: media_player.wohnzimmer
    for: 00:05:00
    platform: state
    to: paused
  condition: []
  action:
  - data: {}
    entity_id: switch.musicbox
    service: switch.turn_off
- id: '1592681919109'
  alias: Licht aus
  description: ''
  trigger:
  - at: 00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.couch
    service: switch.turn_off
- id: '1594164761178'
  alias: Turn pump off after 30 minutes
  description: ''
  trigger:
  - device_id: 6fdb9b50b98441858270f07a66fcd833
    domain: switch
    entity_id: switch.pump
    for:
      hours: 0
      minutes: 30
      seconds: 0
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 6fdb9b50b98441858270f07a66fcd833
    domain: switch
    entity_id: switch.pump
    type: turn_off
  mode: single
- id: '1600034248584'
  alias: Pumpe am Morgen
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - device_id: 6fdb9b50b98441858270f07a66fcd833
    domain: switch
    entity_id: switch.pump
    type: turn_on
  - delay: 00:30:00
  - device_id: 6fdb9b50b98441858270f07a66fcd833
    domain: switch
    entity_id: switch.pump
    type: turn_off
  mode: single
- id: '1600804660957'
  alias: Airpump
  description: ''
  trigger:
  - minutes: /30
    platform: time_pattern
  condition:
  - after: 07:00
    before: '23:00'
    condition: time
  action:
  - data: {}
    entity_id: switch.four
    service: switch.turn_on
  - delay: 00:05:00
  - data: {}
    entity_id: switch.four
    service: switch.turn_off
  mode: single
- id: '1601582985461'
  alias: Increase brightness
  description: ''
  trigger:
  - event_data:
      event: 2002
      id: tradfri_fernbedienung
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data_template:
      brightness: "{% set n = state_attr('light.kitchen_table', 'brightness') + 25\
        \ %} {% if n > 255 %}\n  255\n{% else %}\n  {{ n }}\n{% endif %}\n"
      transition: '1'
    entity_id: light.kitchen_table
    service: light.turn_on
  mode: single
- id: '1601668570889'
  alias: Switch all lights off
  description: ''
  trigger:
  - event_data:
      event: 1002
      id: tradfri_fernbedienung
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - type: turn_off
    device_id: 07b3f203f3e142a6a6045a23ba2b96b4
    entity_id: light.kitchen_table
    domain: light
  - type: turn_off
    device_id: 5d56b331a0ab43b6a225de9a6d823e72
    entity_id: light.living_room
    domain: light
  - service: switch.turn_off
    data: {}
    entity_id: switch.couch
  - service: switch.turn_off
    data: {}
  - service: switch.turn_off
    data: {}
    entity_id: switch.three
  mode: single
- id: '1601923769395'
  alias: Select next bedroom scene
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      event: 5002
      id: tradfri_fernbedienung
  condition: []
  action:
  - service: input_select.select_next
    data: {}
    entity_id: input_select.bedroom_scene_rotation
  mode: single
- id: '1601923782971'
  alias: MuggelnSelected
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.bedroom_scene_rotation
    to: Muggeln
  condition: []
  action:
  - scene: scene.muggeln
  mode: single
- id: '1601923872510'
  alias: LesenSelected
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.bedroom_scene_rotation
    to: Lesen
  condition: []
  action:
  - scene: scene.muggeln2
  mode: single
- id: '1601923924599'
  alias: RomantikSelected
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.bedroom_scene_rotation
    to: Romantik
  condition: []
  action:
  - scene: scene.romantic
  mode: single
- id: '1601928690485'
  alias: BedroomOffSelected
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.bedroom_scene_rotation
    to: Aus
  condition: []
  action:
  - type: turn_off
    device_id: 5d56b331a0ab43b6a225de9a6d823e72
    entity_id: light.living_room
    domain: light
  mode: single
- id: '1601929796392'
  alias: Select next kitchen scene
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      event: 4002
      id: tradfri_fernbedienung
  condition: []
  action:
  - service: input_select.select_next
    data: {}
    entity_id: input_select.kitchen_scene_rotation
  mode: single
- id: '1601929840706'
  alias: DinnerSelected
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.kitchen_scene_rotation
    to: Dinner
  condition: []
  action:
  - scene: scene.dinner
  mode: single
- id: '1601929912770'
  alias: KitchenNormalSelected
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.kitchen_scene_rotation
    to: Normal
  condition: []
  action:
  - scene: scene.kitchennormal
  mode: single
- id: '1601929968399'
  alias: KitchenTableOffSelected
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.kitchen_scene_rotation
    to: Aus
  condition: []
  action:
  - type: turn_off
    device_id: 07b3f203f3e142a6a6045a23ba2b96b4
    entity_id: light.kitchen_table
    domain: light
  mode: single
- id: '1601931194581'
  alias: Toggle bedlight
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      event: 3002
      id: tradfri_fernbedienung
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.three
  mode: single
- id: '1601931366382'
  alias: Toggle couch light
  description: ''
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_fernbedienung
      event: 2002
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.couch
  mode: single
